[2023-10-14T13:25:25.932+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T13:25:25.933+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T13:25:25.935+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:25:25.935+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T13:25:25.948+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:25:25.937+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T13:25:25.950+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T13:25:26.020+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.092 seconds
[2023-10-14T13:25:56.392+0000] {processor.py:157} INFO - Started process (PID=100) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T13:25:56.393+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T13:25:56.396+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:25:56.395+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T13:25:56.399+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:25:56.398+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T13:25:56.400+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T13:25:56.723+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.335 seconds
[2023-10-14T13:26:26.987+0000] {processor.py:157} INFO - Started process (PID=155) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T13:26:27.086+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T13:26:27.096+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:26:27.094+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T13:26:27.112+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:26:27.109+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T13:26:27.113+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T13:26:27.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.352 seconds
[2023-10-14T13:26:57.501+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T13:26:57.942+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T13:26:57.944+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:26:57.944+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T13:26:57.948+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:26:57.947+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T13:26:57.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T13:26:58.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.594 seconds
[2023-10-14T13:27:28.542+0000] {processor.py:157} INFO - Started process (PID=265) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T13:27:28.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T13:27:28.545+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:27:28.544+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T13:27:28.547+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:27:28.547+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T13:27:28.548+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T13:27:28.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.108 seconds
[2023-10-14T13:27:58.775+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T13:27:58.799+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T13:27:58.814+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:27:58.812+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T13:27:58.837+0000] {logging_mixin.py:151} INFO - [2023-10-14T13:27:58.830+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T13:27:58.840+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T13:27:58.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.167 seconds
[2023-10-14T14:28:26.331+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T14:28:26.366+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T14:28:26.369+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:28:26.368+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T14:28:26.373+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:28:26.372+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T14:28:26.374+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T14:28:26.448+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.121 seconds
[2023-10-14T14:28:56.661+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T14:28:56.732+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T14:28:56.735+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:28:56.735+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T14:28:56.740+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:28:56.739+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T14:28:56.740+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T14:28:56.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.127 seconds
[2023-10-14T14:29:26.950+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T14:29:26.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T14:29:26.954+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:29:26.953+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T14:29:26.958+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:29:26.956+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T14:29:26.959+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T14:29:26.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.049 seconds
[2023-10-14T14:29:57.165+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T14:29:57.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T14:29:57.201+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:29:57.200+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T14:29:57.207+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:29:57.205+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T14:29:57.208+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T14:29:57.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.115 seconds
[2023-10-14T14:30:27.783+0000] {processor.py:157} INFO - Started process (PID=248) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T14:30:27.797+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T14:30:27.807+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:30:27.806+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T14:30:27.819+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:30:27.818+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T14:30:27.820+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T14:30:27.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.152 seconds
[2023-10-14T14:30:58.378+0000] {processor.py:157} INFO - Started process (PID=303) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T14:30:58.392+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T14:30:58.395+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:30:58.395+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T14:30:58.405+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:30:58.402+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T14:30:58.417+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T14:30:58.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.142 seconds
[2023-10-14T14:31:28.556+0000] {processor.py:157} INFO - Started process (PID=358) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T14:31:28.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T14:31:28.560+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:31:28.560+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T14:31:28.563+0000] {logging_mixin.py:151} INFO - [2023-10-14T14:31:28.562+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 27
    descarga_pronostico_task = PythonOperator(
    ^
IndentationError: expected an indented block
[2023-10-14T14:31:28.563+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T14:31:28.659+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.106 seconds
[2023-10-14T20:29:49.617+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:29:49.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:29:49.642+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:29:49.641+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:29:49.659+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:29:50.111+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:29:50.110+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-14T20:29:50.144+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:29:50.144+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-14T20:29:50.155+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:29:50.155+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-14T20:29:50.156+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:29:50.156+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:29:50.180+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:29:50.180+0000] {dag.py:2963} INFO - Creating ORM DAG for pronostico_tiempo_dag
[2023-10-14T20:29:50.182+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:29:50.182+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:29:50.284+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.672 seconds
[2023-10-14T20:30:20.427+0000] {processor.py:157} INFO - Started process (PID=86) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:30:20.449+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:30:20.451+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:30:20.451+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:30:20.457+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:30:20.483+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:30:20.483+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:30:20.502+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:30:20.502+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:30:20.544+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.123 seconds
[2023-10-14T20:30:50.955+0000] {processor.py:157} INFO - Started process (PID=141) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:30:50.956+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:30:50.960+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:30:50.959+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:30:50.970+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:30:50.997+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:30:50.997+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:30:51.017+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:30:51.016+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:30:51.053+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.104 seconds
[2023-10-14T20:31:21.445+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:31:21.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:31:21.481+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:31:21.480+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:31:21.496+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:31:21.537+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:31:21.537+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:31:21.577+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:31:21.577+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:31:21.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.201 seconds
[2023-10-14T20:31:52.111+0000] {processor.py:157} INFO - Started process (PID=250) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:31:52.130+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:31:52.133+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:31:52.132+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:31:52.157+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:31:52.198+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:31:52.198+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:31:52.232+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:31:52.232+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:31:52.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.196 seconds
[2023-10-14T20:32:22.523+0000] {processor.py:157} INFO - Started process (PID=305) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:32:22.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:32:22.557+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:32:22.556+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:32:22.580+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:32:22.622+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:32:22.622+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:32:22.651+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:32:22.651+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:32:22.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.216 seconds
[2023-10-14T20:32:53.525+0000] {processor.py:157} INFO - Started process (PID=360) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:32:53.526+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:32:53.531+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:32:53.530+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:32:53.540+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:32:53.567+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:32:53.567+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:32:53.590+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:32:53.590+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:32:53.633+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.112 seconds
[2023-10-14T20:33:24.126+0000] {processor.py:157} INFO - Started process (PID=415) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:33:24.159+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:33:24.162+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:33:24.162+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:33:24.169+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:33:24.195+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:33:24.194+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:33:24.211+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:33:24.211+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:33:24.380+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.260 seconds
[2023-10-14T20:33:54.694+0000] {processor.py:157} INFO - Started process (PID=470) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:33:54.719+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:33:54.723+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:33:54.722+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:33:54.730+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:33:54.753+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:33:54.753+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:33:54.767+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:33:54.767+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:33:54.814+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.127 seconds
[2023-10-14T20:34:25.118+0000] {processor.py:157} INFO - Started process (PID=524) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:34:25.119+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:34:25.123+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:34:25.123+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:34:25.132+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:34:25.160+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:34:25.160+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:34:25.178+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:34:25.177+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:34:25.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.107 seconds
[2023-10-14T20:34:55.259+0000] {processor.py:157} INFO - Started process (PID=578) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:34:55.324+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:34:55.328+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:34:55.328+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:34:55.338+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:34:55.390+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:34:55.390+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:34:55.441+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:34:55.440+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:34:55.488+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.236 seconds
[2023-10-14T20:35:26.024+0000] {processor.py:157} INFO - Started process (PID=632) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:35:26.027+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:35:26.030+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:35:26.029+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:35:26.046+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:35:26.121+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:35:26.121+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:35:26.209+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:35:26.208+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:35:26.310+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.293 seconds
[2023-10-14T20:35:56.724+0000] {processor.py:157} INFO - Started process (PID=687) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:35:56.746+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:35:56.748+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:35:56.748+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:35:56.757+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:35:56.785+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:35:56.784+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:35:56.805+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:35:56.805+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:35:56.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.155 seconds
[2023-10-14T20:36:27.083+0000] {processor.py:157} INFO - Started process (PID=742) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:36:27.084+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:36:27.088+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:36:27.087+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:36:27.097+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:36:27.133+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:36:27.133+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:36:27.155+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:36:27.155+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:36:27.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.138 seconds
[2023-10-14T20:36:57.322+0000] {processor.py:157} INFO - Started process (PID=797) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:36:57.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:36:57.347+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:36:57.346+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:36:57.355+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:36:57.489+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:36:57.488+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:36:57.542+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:36:57.541+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:36:57.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.360 seconds
[2023-10-14T20:37:28.238+0000] {processor.py:157} INFO - Started process (PID=851) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:37:28.243+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:37:28.246+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:37:28.245+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:37:28.253+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:37:28.279+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:37:28.279+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:37:28.300+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:37:28.299+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:37:28.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.277 seconds
[2023-10-14T20:37:59.034+0000] {processor.py:157} INFO - Started process (PID=907) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:37:59.035+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:37:59.038+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:37:59.038+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:37:59.045+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:37:59.068+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:37:59.067+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:37:59.088+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:37:59.088+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:37:59.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.101 seconds
[2023-10-14T20:38:29.808+0000] {processor.py:157} INFO - Started process (PID=961) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:38:29.865+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:38:29.871+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:38:29.870+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:38:29.885+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:38:29.955+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:38:29.955+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:38:30.026+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:38:30.025+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:38:30.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.298 seconds
[2023-10-14T20:39:00.614+0000] {processor.py:157} INFO - Started process (PID=1015) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:39:00.615+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:39:00.620+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:39:00.620+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:39:00.630+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:39:00.836+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:39:00.836+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:39:00.926+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:39:00.926+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:39:01.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.477 seconds
[2023-10-14T20:39:31.258+0000] {processor.py:157} INFO - Started process (PID=1070) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:39:31.279+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:39:31.283+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:39:31.282+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:39:31.289+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:39:31.316+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:39:31.316+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:39:31.337+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:39:31.337+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:39:31.377+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.126 seconds
[2023-10-14T20:40:01.435+0000] {processor.py:157} INFO - Started process (PID=1125) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:40:01.437+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:40:01.441+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:40:01.440+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:40:01.450+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:40:01.480+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:40:01.479+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:40:01.495+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:40:01.495+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:40:01.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.123 seconds
[2023-10-14T20:40:31.644+0000] {processor.py:157} INFO - Started process (PID=1180) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:40:31.680+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:40:31.684+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:40:31.684+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:40:31.698+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:40:31.762+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:40:31.761+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:40:31.826+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:40:31.826+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:40:32.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.400 seconds
[2023-10-14T20:41:02.461+0000] {processor.py:157} INFO - Started process (PID=1235) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:41:02.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:41:02.468+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:41:02.467+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:41:02.485+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:41:02.536+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:41:02.535+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:41:02.574+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:41:02.573+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:41:02.652+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.202 seconds
[2023-10-14T20:41:33.275+0000] {processor.py:157} INFO - Started process (PID=1289) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:41:33.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:41:33.315+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:41:33.314+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:41:33.329+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:41:33.385+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:41:33.385+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:41:33.413+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:41:33.413+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:41:33.472+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.203 seconds
[2023-10-14T20:42:04.130+0000] {processor.py:157} INFO - Started process (PID=1344) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:42:04.133+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:42:04.139+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:42:04.137+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:42:04.148+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:42:04.188+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:42:04.187+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:42:04.214+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:42:04.214+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:42:04.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.140 seconds
[2023-10-14T20:42:34.461+0000] {processor.py:157} INFO - Started process (PID=1398) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:42:34.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:42:34.538+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:42:34.537+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:42:34.553+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:42:34.603+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:42:34.603+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:42:34.647+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:42:34.647+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:42:34.709+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.257 seconds
[2023-10-14T20:43:04.788+0000] {processor.py:157} INFO - Started process (PID=1451) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:43:04.790+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:43:04.795+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:43:04.794+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:43:04.808+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:43:04.888+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:43:04.887+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:43:04.940+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:43:04.939+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:43:05.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.644 seconds
[2023-10-14T20:43:35.523+0000] {processor.py:157} INFO - Started process (PID=1505) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:43:35.525+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:43:35.529+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:43:35.529+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:43:35.540+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:43:35.581+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:43:35.579+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:43:35.621+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:43:35.621+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:43:35.670+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.155 seconds
[2023-10-14T20:44:06.126+0000] {processor.py:157} INFO - Started process (PID=1560) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:44:06.127+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:44:06.130+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:44:06.129+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:44:06.138+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:44:06.166+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:44:06.165+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:44:06.186+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:44:06.185+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:44:06.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.112 seconds
[2023-10-14T20:44:36.879+0000] {processor.py:157} INFO - Started process (PID=1615) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:44:36.902+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:44:36.905+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:44:36.904+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:44:36.912+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:44:36.936+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:44:36.936+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:44:36.953+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:44:36.953+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:44:36.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.120 seconds
[2023-10-14T20:45:07.576+0000] {processor.py:157} INFO - Started process (PID=1669) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:45:07.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:45:07.631+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:45:07.631+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:45:07.647+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:45:07.700+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:45:07.698+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:45:07.769+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:45:07.769+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:45:07.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.233 seconds
[2023-10-14T20:45:38.790+0000] {processor.py:157} INFO - Started process (PID=1723) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:45:38.823+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:45:38.826+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:45:38.826+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:45:38.834+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:45:38.858+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:45:38.858+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:45:38.876+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:45:38.876+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:45:38.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.136 seconds
[2023-10-14T20:46:09.358+0000] {processor.py:157} INFO - Started process (PID=1779) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:46:09.359+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:46:09.371+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:46:09.370+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:46:09.388+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:46:09.436+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:46:09.436+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:46:09.474+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:46:09.474+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:46:09.559+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.216 seconds
[2023-10-14T20:46:40.116+0000] {processor.py:157} INFO - Started process (PID=1833) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:46:40.123+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:46:40.126+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:46:40.125+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:46:40.133+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:46:40.157+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:46:40.157+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:46:40.173+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:46:40.173+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:46:40.208+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.097 seconds
[2023-10-14T20:47:10.742+0000] {processor.py:157} INFO - Started process (PID=1887) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:47:10.743+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:47:10.748+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:47:10.747+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:47:10.765+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:47:10.815+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:47:10.814+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:47:10.844+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:47:10.844+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:47:10.902+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.171 seconds
[2023-10-14T20:47:41.028+0000] {processor.py:157} INFO - Started process (PID=1941) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:47:41.065+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:47:41.068+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:47:41.068+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:47:41.077+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:47:41.104+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:47:41.104+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:47:41.124+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:47:41.124+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:47:41.166+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.142 seconds
[2023-10-14T20:48:11.805+0000] {processor.py:157} INFO - Started process (PID=1996) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:48:11.806+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:48:11.811+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:48:11.810+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:48:11.821+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:48:11.862+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:48:11.862+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:48:11.885+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:48:11.884+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:48:11.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.124 seconds
[2023-10-14T20:48:42.516+0000] {processor.py:157} INFO - Started process (PID=2050) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:48:42.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:48:42.545+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:48:42.545+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:48:42.552+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:48:42.575+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:48:42.574+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:48:42.591+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:48:42.591+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:48:42.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.125 seconds
[2023-10-14T20:49:13.094+0000] {processor.py:157} INFO - Started process (PID=2106) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:49:13.127+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:49:13.130+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:49:13.129+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:49:13.166+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:49:13.188+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:49:13.187+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:49:13.202+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:49:13.202+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:49:13.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.149 seconds
[2023-10-14T20:49:43.363+0000] {processor.py:157} INFO - Started process (PID=2161) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:49:43.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:49:43.372+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:49:43.372+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:49:43.387+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:49:43.444+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:49:43.443+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:49:43.490+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:49:43.489+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:49:43.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.233 seconds
[2023-10-14T20:50:14.133+0000] {processor.py:157} INFO - Started process (PID=2215) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:50:14.222+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:50:14.225+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:50:14.225+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:50:14.234+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:50:14.259+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:50:14.259+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:50:14.278+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:50:14.278+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:50:14.485+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.361 seconds
[2023-10-14T20:50:44.637+0000] {processor.py:157} INFO - Started process (PID=2271) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:50:44.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:50:44.645+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:50:44.644+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:50:44.655+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:50:44.708+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:50:44.707+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:50:44.744+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:50:44.744+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:50:44.821+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.196 seconds
[2023-10-14T20:51:14.958+0000] {processor.py:157} INFO - Started process (PID=2326) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:51:15.006+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:51:15.009+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:51:15.009+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:51:15.033+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:51:15.062+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:51:15.062+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:51:15.079+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:51:15.079+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:51:15.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.172 seconds
[2023-10-14T20:51:45.767+0000] {processor.py:157} INFO - Started process (PID=2381) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:51:45.768+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:51:45.773+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:51:45.772+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:51:45.788+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:51:45.831+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:51:45.830+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:51:45.851+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:51:45.850+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:51:45.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.138 seconds
[2023-10-14T20:52:16.295+0000] {processor.py:157} INFO - Started process (PID=2436) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:52:16.349+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:52:16.351+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:52:16.351+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:52:16.359+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:52:16.385+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:52:16.385+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:52:16.403+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:52:16.402+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:52:16.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.153 seconds
[2023-10-14T20:52:46.613+0000] {processor.py:157} INFO - Started process (PID=2491) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:52:46.615+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:52:46.618+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:52:46.618+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:52:46.628+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:52:46.656+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:52:46.656+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:52:46.674+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:52:46.673+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:52:46.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.099 seconds
[2023-10-14T20:53:17.267+0000] {processor.py:157} INFO - Started process (PID=2546) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:53:17.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:53:17.315+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:53:17.315+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:53:17.325+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:53:17.534+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:53:17.533+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:53:17.546+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:53:17.546+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:53:17.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.375 seconds
[2023-10-14T20:53:48.171+0000] {processor.py:157} INFO - Started process (PID=2601) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:53:48.172+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:53:48.176+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:53:48.175+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:53:48.186+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:53:48.216+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:53:48.216+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:53:48.416+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:53:48.416+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:53:48.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.319 seconds
[2023-10-14T20:54:19.019+0000] {processor.py:157} INFO - Started process (PID=2656) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:54:19.064+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:54:19.068+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:54:19.067+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:54:19.079+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:54:19.110+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:54:19.109+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:54:19.126+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:54:19.126+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:54:19.162+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.150 seconds
[2023-10-14T20:54:49.405+0000] {processor.py:157} INFO - Started process (PID=2711) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:54:49.406+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:54:49.408+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:54:49.408+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:54:49.416+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:54:49.442+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:54:49.442+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:54:49.462+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:54:49.462+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:54:49.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.125 seconds
[2023-10-14T20:55:19.957+0000] {processor.py:157} INFO - Started process (PID=2766) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:55:19.959+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:55:19.963+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:55:19.962+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:55:19.972+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:55:20.002+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:55:20.001+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:55:20.022+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:55:20.022+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:55:20.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.122 seconds
[2023-10-14T20:55:50.659+0000] {processor.py:157} INFO - Started process (PID=2821) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:55:50.660+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:55:50.664+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:55:50.664+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:55:50.675+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:55:50.706+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:55:50.705+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:55:50.726+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:55:50.726+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:55:50.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.112 seconds
[2023-10-14T20:56:21.387+0000] {processor.py:157} INFO - Started process (PID=2876) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:56:21.388+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:56:21.391+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:56:21.391+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:56:21.400+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:56:21.427+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:56:21.426+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:56:21.447+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:56:21.446+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:56:21.489+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.108 seconds
[2023-10-14T20:56:51.863+0000] {processor.py:157} INFO - Started process (PID=2931) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:56:51.863+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:56:51.867+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:56:51.867+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:56:51.877+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:56:51.904+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:56:51.904+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:56:51.922+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:56:51.922+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:56:51.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.096 seconds
[2023-10-14T20:57:22.247+0000] {processor.py:157} INFO - Started process (PID=2986) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:57:22.263+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:57:22.266+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:57:22.265+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:57:22.300+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:57:22.330+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:57:22.329+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:57:22.366+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:57:22.366+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:57:22.431+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.189 seconds
[2023-10-14T20:57:52.978+0000] {processor.py:157} INFO - Started process (PID=3041) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:57:52.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:57:52.998+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:57:52.997+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:57:53.033+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:57:53.110+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:57:53.110+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:57:53.129+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:57:53.129+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:57:53.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.226 seconds
[2023-10-14T20:58:23.392+0000] {processor.py:157} INFO - Started process (PID=3096) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:58:23.398+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:58:23.405+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:58:23.401+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:58:23.445+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:58:23.511+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:58:23.510+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:58:23.565+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:58:23.565+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:58:23.662+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.275 seconds
[2023-10-14T20:58:53.736+0000] {processor.py:157} INFO - Started process (PID=3150) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:58:53.751+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:58:53.754+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:58:53.754+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:58:53.775+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:58:53.830+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:58:53.830+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:58:53.869+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:58:53.868+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:58:53.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.190 seconds
[2023-10-14T20:59:24.295+0000] {processor.py:157} INFO - Started process (PID=3205) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:59:24.298+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:59:24.302+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:59:24.302+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:59:24.374+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:59:24.427+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:59:24.426+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:59:24.465+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:59:24.464+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:59:24.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.269 seconds
[2023-10-14T20:59:54.669+0000] {processor.py:157} INFO - Started process (PID=3260) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T20:59:54.692+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T20:59:54.696+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:59:54.696+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T20:59:54.708+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T20:59:54.746+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:59:54.746+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T20:59:54.767+0000] {logging_mixin.py:151} INFO - [2023-10-14T20:59:54.767+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T20:59:54.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.147 seconds
[2023-10-14T21:00:24.857+0000] {processor.py:157} INFO - Started process (PID=3315) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:00:24.858+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:00:24.862+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:00:24.862+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:00:24.893+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:00:24.945+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:00:24.943+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:00:24.971+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:00:24.971+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:00:25.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.169 seconds
[2023-10-14T21:00:55.658+0000] {processor.py:157} INFO - Started process (PID=3371) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:00:55.671+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:00:55.675+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:00:55.674+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:00:55.691+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:00:55.735+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:00:55.734+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:00:55.760+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:00:55.759+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:00:55.811+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.157 seconds
[2023-10-14T21:01:26.170+0000] {processor.py:157} INFO - Started process (PID=3426) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:01:26.171+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:01:26.175+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:01:26.174+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:01:26.182+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:01:26.204+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:01:26.204+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:01:26.219+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:01:26.219+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:01:26.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.094 seconds
[2023-10-14T21:01:56.304+0000] {processor.py:157} INFO - Started process (PID=3481) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:01:56.324+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:01:56.328+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:01:56.327+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:01:56.335+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:01:56.357+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:01:56.357+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:01:56.377+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:01:56.376+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:01:56.415+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.117 seconds
[2023-10-14T21:02:26.995+0000] {processor.py:157} INFO - Started process (PID=3535) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:02:27.147+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:02:27.202+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:02:27.202+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:02:27.211+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:02:27.248+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:02:27.248+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:02:27.283+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:02:27.283+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:02:27.466+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.476 seconds
[2023-10-14T21:02:58.332+0000] {processor.py:157} INFO - Started process (PID=3597) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:02:58.410+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:02:58.416+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:02:58.412+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:02:58.444+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:02:58.508+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:02:58.508+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:02:58.525+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:02:58.525+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:02:58.560+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.234 seconds
[2023-10-14T21:03:29.087+0000] {processor.py:157} INFO - Started process (PID=3651) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:03:29.263+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:03:29.268+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:03:29.267+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:03:29.279+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:03:29.328+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:03:29.328+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:03:29.346+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:03:29.346+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:03:29.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.483 seconds
[2023-10-14T21:04:00.363+0000] {processor.py:157} INFO - Started process (PID=3705) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:04:00.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:04:00.369+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:04:00.368+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:04:00.380+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:04:00.408+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:04:00.408+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:04:00.428+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:04:00.428+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:04:00.701+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.343 seconds
[2023-10-14T21:04:30.732+0000] {processor.py:157} INFO - Started process (PID=3759) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:04:30.794+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:04:30.797+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:04:30.797+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:04:30.806+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:04:30.832+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:04:30.832+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:04:30.850+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:04:30.850+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:04:30.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.156 seconds
[2023-10-14T21:05:01.233+0000] {processor.py:157} INFO - Started process (PID=3814) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:05:01.234+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:05:01.238+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:05:01.238+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:05:01.249+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:05:01.277+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:05:01.276+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:05:01.294+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:05:01.294+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:05:01.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.112 seconds
[2023-10-14T21:05:31.450+0000] {processor.py:157} INFO - Started process (PID=3869) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:05:31.481+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:05:31.485+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:05:31.484+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:05:31.499+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:05:31.567+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:05:31.566+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:05:31.606+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:05:31.606+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:05:31.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.239 seconds
[2023-10-14T21:06:01.799+0000] {processor.py:157} INFO - Started process (PID=3923) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:06:01.800+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:06:01.802+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:06:01.802+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:06:01.810+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:06:01.834+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:06:01.834+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:06:01.850+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:06:01.850+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:06:01.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.090 seconds
[2023-10-14T21:06:32.424+0000] {processor.py:157} INFO - Started process (PID=3978) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:06:32.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:06:32.494+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:06:32.494+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:06:32.502+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:06:32.528+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:06:32.528+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:06:32.548+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:06:32.548+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:06:32.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.200 seconds
[2023-10-14T21:07:02.758+0000] {processor.py:157} INFO - Started process (PID=4033) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:07:02.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:07:02.762+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:07:02.762+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:07:02.770+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:07:02.794+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:07:02.794+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:07:02.812+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:07:02.812+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:07:03.018+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.267 seconds
[2023-10-14T21:07:33.155+0000] {processor.py:157} INFO - Started process (PID=4088) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:07:33.156+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:07:33.160+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:07:33.160+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:07:33.170+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pronostico_tiempo_dag']) retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:07:33.213+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:07:33.212+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T21:07:33.232+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:07:33.232+0000] {dag.py:3722} INFO - Setting next_dagrun for pronostico_tiempo_dag to None, run_after=None
[2023-10-14T21:07:33.275+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.124 seconds
[2023-10-14T21:07:46.019+0000] {processor.py:157} INFO - Started process (PID=4104) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:07:46.125+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:07:46.129+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:07:46.128+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:07:46.511+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:07:46.208+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:07:46.585+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:07:46.840+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.826 seconds
[2023-10-14T21:08:17.161+0000] {processor.py:157} INFO - Started process (PID=4158) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:08:17.162+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:08:17.165+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:08:17.165+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:08:17.183+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:08:17.179+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:08:17.184+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:08:17.252+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.096 seconds
[2023-10-14T21:08:47.966+0000] {processor.py:157} INFO - Started process (PID=4213) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:08:48.026+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:08:48.030+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:08:48.029+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:08:48.044+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:08:48.038+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:08:48.050+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:08:48.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.167 seconds
[2023-10-14T21:09:18.929+0000] {processor.py:157} INFO - Started process (PID=4268) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:09:18.930+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:09:18.932+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:09:18.932+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:09:18.945+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:09:18.941+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:09:18.946+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:09:19.023+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.102 seconds
[2023-10-14T21:09:49.183+0000] {processor.py:157} INFO - Started process (PID=4323) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:09:49.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:09:49.199+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:09:49.198+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:09:49.210+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:09:49.207+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:09:49.210+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:09:49.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.075 seconds
[2023-10-14T21:10:19.510+0000] {processor.py:157} INFO - Started process (PID=4378) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:10:19.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:10:19.514+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:10:19.514+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:10:19.531+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:10:19.528+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:10:19.532+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:10:19.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.097 seconds
[2023-10-14T21:10:50.123+0000] {processor.py:157} INFO - Started process (PID=4433) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:10:50.172+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:10:50.174+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:10:50.173+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:10:50.186+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:10:50.183+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:10:50.187+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:10:50.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.109 seconds
[2023-10-14T21:11:20.854+0000] {processor.py:157} INFO - Started process (PID=4488) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:11:20.856+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:11:20.857+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:11:20.857+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:11:20.869+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:11:20.866+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:11:20.870+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:11:20.950+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.099 seconds
[2023-10-14T21:11:51.329+0000] {processor.py:157} INFO - Started process (PID=4542) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:11:51.331+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:11:51.332+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:11:51.332+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:11:51.344+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:11:51.341+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:11:51.345+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:11:51.372+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.050 seconds
[2023-10-14T21:12:22.259+0000] {processor.py:157} INFO - Started process (PID=4597) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:12:22.260+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:12:22.262+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:12:22.261+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:12:22.292+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:12:22.289+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:12:22.292+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:12:22.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.086 seconds
[2023-10-14T21:12:53.178+0000] {processor.py:157} INFO - Started process (PID=4652) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:12:53.229+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:12:53.230+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:12:53.230+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:12:53.289+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:12:53.282+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:12:53.298+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:12:53.366+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.193 seconds
[2023-10-14T21:13:24.034+0000] {processor.py:157} INFO - Started process (PID=4707) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:13:24.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:13:24.038+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:13:24.038+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:13:24.053+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:13:24.050+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:13:24.055+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:13:24.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.099 seconds
[2023-10-14T21:13:54.642+0000] {processor.py:157} INFO - Started process (PID=4762) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:13:54.654+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:13:54.656+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:13:54.655+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:13:54.667+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:13:54.664+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:13:54.667+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:13:54.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.080 seconds
[2023-10-14T21:14:25.231+0000] {processor.py:157} INFO - Started process (PID=4817) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:14:25.232+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:14:25.234+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:14:25.233+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:14:25.249+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:14:25.246+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:14:25.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:14:25.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.112 seconds
[2023-10-14T21:14:56.263+0000] {processor.py:157} INFO - Started process (PID=4872) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:14:56.270+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:14:56.272+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:14:56.271+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:14:56.282+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:14:56.279+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:14:56.282+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:14:56.321+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.069 seconds
[2023-10-14T21:15:26.940+0000] {processor.py:157} INFO - Started process (PID=4927) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:15:26.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:15:26.947+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:15:26.947+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:15:26.963+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:15:26.960+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:15:26.964+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:15:27.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.104 seconds
[2023-10-14T21:15:57.757+0000] {processor.py:157} INFO - Started process (PID=4981) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:15:57.761+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:15:57.764+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:15:57.762+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:15:57.783+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:15:57.779+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:15:57.787+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:15:57.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.123 seconds
[2023-10-14T21:16:28.400+0000] {processor.py:157} INFO - Started process (PID=5036) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:16:28.436+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:16:28.438+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:16:28.437+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:16:28.449+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:16:28.446+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:16:28.450+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:16:28.505+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.113 seconds
[2023-10-14T21:16:59.274+0000] {processor.py:157} INFO - Started process (PID=5091) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:16:59.276+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:16:59.280+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:16:59.279+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:16:59.294+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:16:59.290+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:16:59.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:16:59.351+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.087 seconds
[2023-10-14T21:17:29.880+0000] {processor.py:157} INFO - Started process (PID=5146) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:17:29.921+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:17:29.922+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:17:29.921+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:17:29.940+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:17:29.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:17:29.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:17:30.105+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.230 seconds
[2023-10-14T21:18:00.276+0000] {processor.py:157} INFO - Started process (PID=5198) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:18:00.317+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:18:00.318+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:18:00.318+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:18:00.352+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:18:00.349+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:18:00.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:18:00.394+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.124 seconds
[2023-10-14T21:18:30.957+0000] {processor.py:157} INFO - Started process (PID=5252) to work on /opt/airflow/dags/tiempo.py
[2023-10-14T21:18:30.959+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/tiempo.py for tasks to queue
[2023-10-14T21:18:30.960+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:18:30.960+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/tiempo.py
[2023-10-14T21:18:30.968+0000] {logging_mixin.py:151} INFO - [2023-10-14T21:18:30.966+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/tiempo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tiempo.py", line 36, in <module>
    obtener_pronostico_op = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'obtener_pronostico_Córdoba, AR' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-10-14T21:18:30.969+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/tiempo.py
[2023-10-14T21:18:31.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/tiempo.py took 0.073 seconds
